config/routes.rb
Rails.application.routes.draw do




  namespace :admin do
    resources :progresses
    resources :progress_attachments
    root to: "progresses#index"
  end


  resources :progresses
  resources :contacts, only: [:new, :create]
  resources :supports, only: [:new, :create]

  root "home#index"

end

app/controllers/admin/progresses_controller.rb
module Admin

  class ProgressesController < Admin::ApplicationController

    def create
       @progress = Progress.new(progress_params)

       respond_to do |format|
         if @progress.save
           unless params[:progress_attachments].nil?
             params[:progress_attachments]['image'].each do |a|
               @progress_attachment = @progress.progress_attachments.create!(:image => a)
             end

           end
           format.html { redirect_to admin_progresses_path, notice: 'Progress was successfully created.' }
         else
           format.html {
             render action: 'new',
             locals: { page: Administrate::Page::Form.new(dashboard, resource_class.new) }
           }
         end
       end
     end

     private

     def progress_params
        params.require(:progress).permit(:title, :content, :date, :main_image, progress_attachments_attributes: [:id, :progress_id, :image])
     end

  end

end


# unless params[:progress_attachments].nil?
#   params[:progress_attachments]['image'].each do |a|
#     @progress_attachment = @progress.progress_attachments.create!(:image => a)
#   end
# end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController


  def index
    @progresses = Progress.all
  end

  def show
    @progress = Progress.find(params[:id])
    @progress_attachments = @progress.progress_attachments.all
  end

  def new
     @progress = Progress.new
     @progress_attachment = @progress.progress_attachments.build
  end

   private
     def progress_params
        params.require(:progress).permit(:title, :content, :date, :main_image, progress_attachments_attributes: [:id, :progress_id, :image])
     end
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/views/progresses/index.html.slim
.container
  .section
    .row
       .col-xs-12
        h1.text-gold 
          |Work In Progress  [
          = @progresses.count 
          | ]
  hr
  #progresses.transitions-enabled
    - @progresses.each do |progress|
      .box.panel.panel-default
        = link_to (image_tag progress.main_image.url), progress
        .panel-body
          h4.text-gold = progress.title.upcase
          h5 = progress.date
          small = truncate(progress.content, length: 150)
          / = link_to "Open", progress_path(progress),
          / class:"btn btn-primary btn-thumb"
          / 
      
        
          / .col-xs-12.col-sm-6.col-md-4
          /   .col-xs-12.progress_content

app/views/progresses/show.html.slim
.container
  .section
    .col-xs-12
      h2 = @progress.date
      h3 = @progress.title
    
      p  = simple_format(@progress.content)
      br
    .col-xs-12
      #diaporama.carousel.slide
        .carousel-inner
          - @progress_attachments.each_with_index do |p, index|
            .item  class= "#{ "active" if index == 0 }"
              = image_tag p.image_url, class: "diapo"
      
              
          a.left.carousel-control data-slide="prev" href="#diaporama" 
            span.glyphicon.glyphicon-chevron-left
          a.right.carousel-control data-slide="next" href="#diaporama" 
            span.glyphicon.glyphicon-chevron-right
        br 
        #miniatures
          .row
            .col-xs-12
              img-responsive alt="" data-slide-to="0" data-target="#diaporama" 
              - @progress_attachments.each do |p|
                = image_tag p.image_url, class: "mini_diapo"
          
          = link_to "Back", progresses_path, 
            class:"btn btn-thumb"


            
      