config/routes.rb
Rails.application.routes.draw do




  namespace :admin do
    resources :progresses
    resources :progress_attachments
    root to: "progresses#index"
  end


  resources :progresses
  resources :contacts, only: [:new, :create]
  resources :supports, only: [:new, :create]

  root "home#index"

end

app/models/progress_attachment.rb
class ProgressAttachment < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :progress
  validates :image, presence: true

  
end

app/controllers/admin/progress_attachments_controller.rb
module Admin
  class ProgressAttachmentsController < ApplicationController
    before_action :set_progress_attachment


    def create
      @progress_attachment = ProgressAttachment.new(progress_attachment_params)

      respond_to do |format|
        if @progress_attachment.save
          format.html { redirect_to @progress_attachment, notice: 'Progress attachment was successfully created.' }
          format.json { render :show, status: :created, location: @progress_attachment }
        else
          format.html { render :new }
          format.json { render json: @progress_attachment.errors, status: :unprocessable_entity }
        end
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_progress_attachment
        @progress_attachment = ProgressAttachment.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def progress_attachment_params
        params.require(:progress_attachment).permit(:progress_id, :image)
      end
  end

end

app/controllers/progress_attachments_controller.rb
class ProgressAttachmentsController < ApplicationController
  before_action :set_progress_attachment, only: [:show, :edit, :update, :destroy]


  def index
    @progress_attachments = ProgressAttachment.all
  end


  def show
  end


  def new
    @progress_attachment = ProgressAttachment.new
  end

  def edit
  end


  def create
    @progress_attachment = ProgressAttachment.new(progress_attachment_params)

    respond_to do |format|
      if @progress_attachment.save
        format.html { redirect_to @progress_attachment, notice: 'Progress attachment was successfully created.' }
        format.json { render :show, status: :created, location: @progress_attachment }
      else
        format.html { render :new }
        format.json { render json: @progress_attachment.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @progress_attachment.update(progress_attachment_params)
        format.html { redirect_to @progress_attachment, notice: 'Progress attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @progress_attachment }
      else
        format.html { render :edit }
        format.json { render json: @progress_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progress_attachments/1
  # DELETE /progress_attachments/1.json
  def destroy
    @progress_attachment.destroy
    respond_to do |format|
      format.html { redirect_to progress_attachments_url, notice: 'Progress attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress_attachment
      @progress_attachment = ProgressAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def progress_attachment_params
      params.require(:progress_attachment).permit(:progress_id, :image)
    end
end

app/helpers/progress_attachments_helper.rb
module ProgressAttachmentsHelper
end

app/views/progress_attachments/_form.html.erb
<%= simple_form_for(@progress_attachment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :progress_id %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/progress_attachments/edit.html.erb
<h1>Editing Progress Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @progress_attachment %> |
<%= link_to 'Back', progress_attachments_path %>

app/views/progress_attachments/index.html.erb
<% @courses.in_groups_of(3, false).each do |group| %>
<div class="row">
<% group.each do |course|%>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= truc.machin %>
      <%= bidule.machin %>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/progress_attachments/index.html.slim
h1 Listing Progress Attachments
- @progress_attachments.each do |progress_attachment|

  = progress_attachment.progress.image_url
  

app/views/progress_attachments/new.html.erb
<h1>New Progress Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', progress_attachments_path %>

app/views/progress_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Progress:</strong>
  <%= @progress_attachment.progress_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @progress_attachment.image %>
</p>

<%= link_to 'Edit', edit_progress_attachment_path(@progress_attachment) %> |
<%= link_to 'Back', progress_attachments_path %>