config/routes.rb
Rails.application.routes.draw do




  namespace :admin do
    resources :progresses
    resources :progress_attachments
    root to: "progresses#index"
  end


  resources :progresses
  resources :contacts, only: [:new, :create]
  resources :supports, only: [:new, :create]

  root "home#index"

end

app/views/layouts/_footer.html.slim
.footer
  .container
    .row.footer-content
        .col-xs-4.col-sm-4.col-md-4.col-lg-4.text-center
          = link_to new_support_path(@support) do
            i.fa.fa-bug.fa-fw.text-inverse
            small.footer-text
              span<> Report a bug or typos

        .col-xs-4.col-sm-4.col-md-4.col-lg-4.text-center
          = link_to new_contact_path(@contact) do
            i.fa.fa-envelope-o.fa-fw.hub.text-inverse
            small.footer-text
              span<> Contact me
              
        .col-xs-4.col-sm-4.col-md-4.col-lg-4.text-center
          small.footer-text
            |© 
            span<>
            = Date.today.year 
            span<> Nelly Duclos
            .row
              .col-xs-12
              - start_time =  "2016-07-24 00:00:00 "
              - end_time   =  Time.now
              - date = distance_of_time_in_words(start_time, end_time).to_s
              small.footer-text Last update #{date} ago
          

app/views/layouts/_nav.html.slim
.navbar
  .container-fluid
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target="#navbar-ex-collapse"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      .navbar-brand.leschner-brand
        = link_to "LESCHNER", root_path
    #navbar-ex-collapse.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li.active
          = link_to "Home", root_path
        li
          =link_to "What I Do", page_path('what_i_do')
        li
          =link_to "Musicians & Leschner Gears", page_path('musicians')
        li
          =link_to "In Progress", progresses_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Leschner guitars
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    meta name="viewport" content="width=device-width, initial-scale=1"
    scrip type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"
    script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"
    link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"
    link href="//pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css" rel="stylesheet" type="text/css"

  body
  = render partial:"layouts/nav"

  .wrapper
    .container
      - flash.each do |name, msg|
        - if msg.is_a?(String)
          div class=("alert alert-#{name == :notice ? "success" : "error"}") 
            a.close data-dismiss="alert" 
              | &times;
            = content_tag :div, msg, :id => "flash_#{name}"
            
    = yield
  = render partial:"layouts/footer"